### ISSUE TITLE
IE 11 and Edge Failures

### ISSUE THREAD

**Issue by patrickmichalina** [KevCJones/plugin-scss#15]
Anyone else having issues with IE 11 or Edge?

IE 11:

```
SCRIPT0: Out of stack space
sass.worker.js (7,1)
```

Edge:

```
SCRIPT5022: (SystemJS) SyntaxError: Unterminated string constant
    Evaluating http://localhost:3000/app/app.styles.scss
system.src.js (5123,3)
```

Chrome works as expected.

**Comment by gertsonderby** [comment]
Why was this closed? I'm running into this now. Do you have a solution?

**Comment by patrickmichalina** [comment]
@gertsonderby I did resolve this awhile ago, but cannot remember exactly what I did. It had to do with the way I was importing partial SCSS files - not sure. The underlying issue appears to be, given a large application and set of styles, when SystemJS is processing all the javascript and scss files, it reaches an arbitrary IE (windows?) JavaScript memory limit. 

I think by serving a bundle instead of every file locally, you can avoid this issue (since the styles by this point have been compiled and are no longer being processed at runtime).
