### ISSUE TITLE
`jspm bundle` and `jspm build` doesn't seem to work when I use this plugin.

### ISSUE THREAD

**Issue by mr-rodgers** [KevCJones/plugin-scss#2]
Whenever I used this plugin to import sass text from into a typescript file like so

```
import styleText from './app.component.scss!';
```

`jspm build` just gives me empty output and doesn't generate a .js file. If I comment out the import, the build works fine.

**Comment by kevcjones-archived** [comment]
Strange, i have a working demo using it that is using JSPM build. If you have some same work i would be happy to see if i can spot the difference for you.

Looking into it, I was able to replicate the error you experienced if i created some invalid scss, which does make me thing i need better error reporting in the very least.  Does it convert okay in this online checker? http://www.sassmeister.com/

**Comment by kevcjones-archived** [comment]
I've patched the plugin so you can install it again 
`jspm install scss -f`

Its a quick output but i've not worked out how to get that to throw the error during the build/bundle phase. However at runtime, you should see errors from the plugin if there are any in your scss code.

Let me know how you get on.

**Comment by kevcjones-archived** [comment]
So i've hot-fixed onto v0.2.5 a solution i'm happy enough with for now. 

### What you were seeing (as best i can tell)

A silent 'failed bundle' , the process was dying somewhere inside jspm's builder during the 'translate' hook. During a normal runtime test, this was ok, the promises rejection bubbled up to the console on the browser. However on bundle and build (within the terminal) it did not (i don't have an answer to why on that one).

### So what does it do now

Sass errors are pushed to the terminal and browser console in a similar way. You will no longer think its worked when it has not. 

I'm going away for a week, i won't be able to respond after tomorrow evening. Hopefully this helps you.

**Comment by kevcjones-archived** [comment]
Oops wrong button - apologies, won't close until you've found your issue.

**Comment by mr-rodgers** [comment]
The update prints out the error. 

```
     Creating the single-file build for glotpod-web...
 [plugin-scss]  Stacklite :: github:KevCJones/plugin-scss/sass-inject-build.js -> npm:sass.js
 [plugin-scss]  Error: File to import not found or unreadable: jspm:styles/palette
       Parent style sheet: stdin
        on line 1 of stdin
>> @import 'jspm:styles/palette';
   ^
```

I was using the import syntax described in #1 to import one of my own scss files:

``` scss
@import 'jspm:styles/palette';
```

I also have this set in my jspm.browser.js:

``` javascript
SystemJS.config({
  paths: {
    "github:*": "/jspm_packages/github/*",
    "npm:*": "/jspm_packages/npm/*",
    "styles*": "src/styles*"
  }
});
```

This appears to work in the browser, as angular loads the styles for the component just fine. I have no idea how jspm works internally, but the name of the config file hints that it probably doesn't get loaded at build/bundle time so that's probably my problem right there.

Thanks for your help!

**Comment by kevcjones-archived** [comment]
Its hard to say from that snippet, but i can suggest a couple of things, and assure you it works for me. So i think that its possible a base folder thing but the fact it works ok for your runtime but not for your build.

I'll describe the touch points JSPM/SystemJS. Firstly i prefer NOT to run my server from the root folder so you will have to adjust the below to match your needs.

inside my package.json

```
...
"jspm": {
    "directories": {
      "baseURL": "www"
    },
```

inside my config.js

```
paths: {
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*",
    "styles*": "src/styles*"
  },
```

In fact looking at yours i can see you have a leading slash (indicating root path) for the defaults but have opted for a relative path for the styles path. I imagine this is where you might be having issues, perhaps between those two things you  have enough to see the issue?

One test might be to remove the jspm:styles and try an explicit relative path first. If you get the working you'll see what configuration you need to convert the path of styles correctly.

Cheers and thanks for the issue, it spurned an addition thats already improved my own usage.
