### ISSUE TITLE
System.config configuration

### ISSUE THREAD

**Issue by frederikschubert** [KevCJones/plugin-scss#5]
Could you integrate [this](https://github.com/mobilexag/plugin-sass/commit/50d6334e6077b1af0da9e4659edddcac3a4211c0) commit into your plugin?

**Comment by kevcjones-archived** [comment]
i can and i will (thanks for doing the hard work)

**Comment by kevcjones-archived** [comment]
[Config now supported](https://github.com/KevCJones/plugin-scss/commit/e44ef80357d9f684fa9d5541940f30af24fb6118)
Pushed to v0.2.6
