### ISSUE TITLE
Autoprefixer support

### ISSUE THREAD

**Issue by frederikschubert** [KevCJones/plugin-scss#6]
Could you integrate autoprefixer into your plugin and make it configurable via System.config?

**Comment by kevcjones-archived** [comment]
i can and i will - i'll try to get this done today, if not it will have to wait until Sunday after from travels.

**Comment by kevcjones-archived** [comment]
ignore my blinder with the labels ^ i misunderstood.

**Comment by kevcjones-archived** [comment]
[Auto-prefixer now processes css if set in config](https://github.com/KevCJones/plugin-scss/commit/f4014c7e52942b7b8408e1931ec8fe38c92bd6aa)

**Comment by frederikschubert** [comment]
Great! Thank you for your fast response! It might be useful to add this plugin to the systemjs readme besides the other sass plugin. :)

**Comment by kevcjones-archived** [comment]
Good idea, [done it, let's see](https://github.com/systemjs/systemjs/pull/1204)
